
server:
  port: 8081

spring:
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin
    embedded:
      enabled: false
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: "*"
